trigger:
 branches:
   include:
     - main
     - feature

pool:  prod-pool

parameters:
  - name:  environment
    type:  string
    default: dev
    values:
      - dev
      - qa
      - prod

stages:
  - stage: FirstStage
    displayName: terraformfmt
    jobs:
      - job: fmt
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                terraform version
                
                terraform fmt -check -recursive

  - stage: SecondStage
    displayName: init/validate
    jobs:
      - job: InitValidate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'D:\Agent\vsts-agent-win-x64-4.274.1\_work\2'
              backendServiceArm: 'prod-sc'
              backendAzureRmStorageAccountName: 'gurustg26'
              backendAzureRmContainerName: 'gurucnt26'
              backendAzureRmKey: 'guruji.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: 'D:\Agent\vsts-agent-win-x64-4.274.1\_work\2'

  - stage: ThirdStage
    displayName: Plan
    jobs:
      - job: terraformplan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)'
              backendServiceArm: 'prod-sc'
              backendAzureRmStorageAccountName: 'gurustg26'
              backendAzureRmContainerName: 'gurucnt26'
              backendAzureRmKey: 'guruji.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(Build.SourcesDirectory)'
              environmentServiceNameAzureRM: 'prod-sc'
              commandOptions: '-var-file="$(Build.SourcesDirectory)\infrastructure\environments\dev\terraform.tfvars"'
          

  - stage: FourthStage
    displayName: ManualValidation
    jobs:
      - job: manaulvalidation
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'sp2529437@gmaul.com'
              instructions: 'Review the Terraform plan and approve the deployment'